name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.30.0
    with:
      image: 'ghcr.io/radiorabe/s2i-core' 
      name: 's2i-core'
      display-name: 'RaBe S2I Core Minimal'
      tags: 'minimal rhel9 rabe s2i'
      cosign-base-image-only: true
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@v0.30.0
