name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@c7aef9928f610ec51b44f84debf2321189276d54 # v0.41.3
    with:
      image: 'ghcr.io/radiorabe/s2i-core' 
      name: 's2i-core'
      display-name: 'RaBe S2I Core Minimal'
      tags: 'minimal rhel9 rabe s2i'
      cosign-base-image-only: true
      platforms: "linux/amd64,linux/arm64"
      docker-daemon-config: |
        {
          "features": {
            "containerd-snapshotter": true
          }
        }
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@c7aef9928f610ec51b44f84debf2321189276d54 # v0.41.3
