name: Run semantic-release

on:
  push:
    branches:
      - main
      - release/*

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/semantic-release.yaml@v0.8.7
    secrets:
      RABE_ITREAKTION_GITHUB_TOKEN: ${{ secrets.RABE_ITREAKTION_GITHUB_TOKEN }}
